//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class DS_ContentAds
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DS_ContentAds()
        {
            this.DS_TVContentAds = new HashSet<DS_TVContentAds>();
        }
    
        public decimal id { get; set; }
        public Nullable<decimal> content_id { get; set; }
        public Nullable<decimal> ad_id { get; set; }
        public Nullable<decimal> live_id { get; set; }
        public Nullable<int> interval { get; set; }
        public Nullable<short> position { get; set; }
        public Nullable<short> type { get; set; }
        public Nullable<short> status { get; set; }
        public Nullable<long> createDateTime { get; set; }
        public string description { get; set; }
        public Nullable<byte> shuffle { get; set; }
        public Nullable<int> secondViewed { get; set; }
        public Nullable<decimal> companyId { get; set; }
    
        public virtual DS_Ads DS_Ads { get; set; }
        public virtual DS_Contents DS_Contents { get; set; }
        public virtual DS_Lives DS_Lives { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DS_TVContentAds> DS_TVContentAds { get; set; }
    }
}
