//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class DS_Lives
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DS_Lives()
        {
            this.DS_ContentAds = new HashSet<DS_ContentAds>();
            this.DS_LivePrograms = new HashSet<DS_LivePrograms>();
        }
    
        public decimal id { get; set; }
        public string title { get; set; }
        public string url { get; set; }
        public Nullable<short> status { get; set; }
        public Nullable<short> type { get; set; }
        public string description { get; set; }
        public string channel { get; set; }
        public Nullable<decimal> companyId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DS_ContentAds> DS_ContentAds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DS_LivePrograms> DS_LivePrograms { get; set; }
    }
}
