//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class DS_Maps
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DS_Maps()
        {
            this.DS_Stores = new HashSet<DS_Stores>();
        }
    
        public decimal id { get; set; }
        public string title { get; set; }
        public Nullable<short> floor { get; set; }
        public string image { get; set; }
        public Nullable<short> status { get; set; }
        public Nullable<short> type { get; set; }
        public Nullable<decimal> companyId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DS_Stores> DS_Stores { get; set; }
    }
}
