//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class DS_StoreEvents
    {
        public decimal id { get; set; }
        public Nullable<decimal> store_id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string image { get; set; }
        public Nullable<short> status { get; set; }
        public Nullable<short> type { get; set; }
        public Nullable<int> date { get; set; }
        public Nullable<decimal> companyId { get; set; }
    
        public virtual DS_Stores DS_Stores { get; set; }
    }
}
