//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class DS_Stores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DS_Stores()
        {
            this.DS_StoreEvents = new HashSet<DS_StoreEvents>();
        }
    
        public decimal id { get; set; }
        public Nullable<decimal> category_id { get; set; }
        public Nullable<decimal> map_id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public Nullable<int> unit { get; set; }
        public string phone1 { get; set; }
        public string phone2 { get; set; }
        public Nullable<short> status { get; set; }
        public Nullable<short> type { get; set; }
        public Nullable<int> x { get; set; }
        public Nullable<int> y { get; set; }
        public string image { get; set; }
        public string startWorkTime { get; set; }
        public string endWorkTime { get; set; }
        public string workingDay { get; set; }
        public Nullable<decimal> companyId { get; set; }
    
        public virtual DS_Maps DS_Maps { get; set; }
        public virtual DS_StoreCategories DS_StoreCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DS_StoreEvents> DS_StoreEvents { get; set; }
    }
}
