//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class DS_TVContents
    {
        public decimal id { get; set; }
        public Nullable<decimal> tv_id { get; set; }
        public Nullable<decimal> content_id { get; set; }
        public Nullable<int> startTime { get; set; }
        public Nullable<int> endTime { get; set; }
        public Nullable<int> duration { get; set; }
        public Nullable<short> status { get; set; }
        public Nullable<short> type { get; set; }
        public Nullable<long> lastViewed { get; set; }
        public Nullable<decimal> companyId { get; set; }
    
        public virtual DS_Contents DS_Contents { get; set; }
        public virtual DS_TVs DS_TVs { get; set; }
    }
}
