//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class DS_TVContentAds
    {
        public decimal id { get; set; }
        public Nullable<decimal> content_ad_id { get; set; }
        public Nullable<long> datetime { get; set; }
        public Nullable<decimal> tv_id { get; set; }
        public Nullable<short> status { get; set; }
        public Nullable<decimal> companyId { get; set; }
    
        public virtual DS_ContentAds DS_ContentAds { get; set; }
        public virtual DS_TVs DS_TVs { get; set; }
    }
}
