//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class DS_Videos
    {
        public decimal id { get; set; }
        public Nullable<decimal> category_id { get; set; }
        public string title { get; set; }
        public Nullable<long> createDateTime { get; set; }
        public Nullable<int> duration { get; set; }
        public string description { get; set; }
        public Nullable<int> rank { get; set; }
        public Nullable<int> hits { get; set; }
        public Nullable<short> status { get; set; }
        public Nullable<short> type { get; set; }
        public string file_name { get; set; }
        public Nullable<decimal> companyId { get; set; }
    
        public virtual DS_VideoCategories DS_VideoCategories { get; set; }
    }
}
