//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalServices
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DigitalSignageEntities : DbContext
    {
        public DigitalSignageEntities()
            : base("name=DigitalSignageEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DS_AdItems> DS_AdItems { get; set; }
        public virtual DbSet<DS_Ads> DS_Ads { get; set; }
        public virtual DbSet<DS_Alarms> DS_Alarms { get; set; }
        public virtual DbSet<DS_Company> DS_Company { get; set; }
        public virtual DbSet<DS_ContentAds> DS_ContentAds { get; set; }
        public virtual DbSet<DS_Contents> DS_Contents { get; set; }
        public virtual DbSet<DS_ContentTypes> DS_ContentTypes { get; set; }
        public virtual DbSet<DS_LivePrograms> DS_LivePrograms { get; set; }
        public virtual DbSet<DS_Lives> DS_Lives { get; set; }
        public virtual DbSet<DS_Maps> DS_Maps { get; set; }
        public virtual DbSet<DS_News> DS_News { get; set; }
        public virtual DbSet<DS_StoreCategories> DS_StoreCategories { get; set; }
        public virtual DbSet<DS_StoreEvents> DS_StoreEvents { get; set; }
        public virtual DbSet<DS_Stores> DS_Stores { get; set; }
        public virtual DbSet<DS_TVCategories> DS_TVCategories { get; set; }
        public virtual DbSet<DS_TVContentAds> DS_TVContentAds { get; set; }
        public virtual DbSet<DS_TVContents> DS_TVContents { get; set; }
        public virtual DbSet<DS_TVs> DS_TVs { get; set; }
        public virtual DbSet<DS_Users> DS_Users { get; set; }
        public virtual DbSet<DS_VideoCategories> DS_VideoCategories { get; set; }
        public virtual DbSet<DS_Videos> DS_Videos { get; set; }
    }
}
